---
- hosts: localhost
  become: true
  tasks:

    - name: install dev tools
      apt:
          pkg:
              - bc
              - bison
              - flex
              - libssl-dev
              - libncurses5-dev

